CREATE TABLE PLAYERS(
  ID BIGINT AUTO_INCREMENT,
  NAME VARCHAR(255),
  ATTACK INT,
  MOVEMENT_SPEED INT,
  HEALTH INT,
  PLAYER_TYPE VARCHAR(255),
  POSITION_X INT,
  POSITION_Y INT,
  SCORE INT
);

INSERT INTO PLAYERS (NAME, ATTACK, MOVEMENT_SPEED, HEALTH, PLAYER_TYPE, POSITION_X, POSITION_Y, SCORE)
VALUES ('Bob the Crusher',10,4,15,'HeavyDude',0,0,0);

INSERT INTO PLAYERS (NAME, ATTACK, MOVEMENT_SPEED, HEALTH, PLAYER_TYPE, POSITION_X, POSITION_Y, SCORE)
VALUES ('Speedy Dżordż',7,10,12,'FastDude',0,0,0);